"""Initial migration

Revision ID: 028affd6086a
Revises: 
Create Date: 2025-12-05 23:56:29.380218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028affd6086a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create index (Safe to keep)
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_data_recorded_at'), ['recorded_at'], unique=False)
    
    # 2. Manually add foreign keys to auth.users (if they don't exist)
    # Using PL/pgSQL to check for existence first to avoid errors
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_device_states_user_id') THEN 
                ALTER TABLE device_states 
                ADD CONSTRAINT fk_device_states_user_id 
                FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
            END IF;
            
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sensor_data_user_id') THEN 
                ALTER TABLE sensor_data 
                ADD CONSTRAINT fk_sensor_data_user_id 
                FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop the manually created constraints
    op.execute("ALTER TABLE device_states DROP CONSTRAINT IF EXISTS fk_device_states_user_id")
    op.execute("ALTER TABLE sensor_data DROP CONSTRAINT IF EXISTS fk_sensor_data_user_id")
    
    # 2. Drop the index
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_data_recorded_at'))

    # ### end Alembic commands ###
